---
- name: strongSwan setup
  hosts: all
  become: true
  roles:
    - role: strongswan
      vars:
        strongswan__con_name: "{{ strongswan_con_name }}"
        strongswan__left: "{{ strongswan_left }}"
        strongswan__right: "{{ strongswan_right }}"
        strongswan__leftsubnet: "{{ strongswan_leftsubnet }}"
        strongswan__rightsubnet: "{{ strongswan_rightsubnet }}"
        strongswan__psk: "{{ vault__strongswan__psk }}"
