---
incus_host_idmap_enabled: true
incus_host_idmap_owner: root
incus_host_idmap_start: 1000000
incus_host_idmap_count: 1000000000
incus_host_idmap_files:
  - /etc/subuid
  - /etc/subgid
incus_host_idmap_service: incus.service
...
