---
- name: Deploy HashiCorp Vault
  become: true
  hosts: "{{ vault_target | default('vault') }}"
  gather_facts: true
  roles:
    - role: lit.supplementary.vault_deploy
      tags:
        - vault
        - vault_deploy

    - role: lit.supplementary.vault_bootstrap
      when: vault_bootstrap_enabled | default(true) | bool
      tags:
        - vault
        - vault_bootstrap

    - role: lit.supplementary.vault_validate
      when: vault_validate_enabled | default(true) | bool
      tags:
        - vault
        - vault_validate

    - role: lit.supplementary.vault_ops
      when: vault_ops_enabled | default(false) | bool
      tags:
        - vault
        - vault_ops

    - role: lit.supplementary.vault_config
      when: vault_config_enabled | default(false) | bool
      tags:
        - vault
        - vault_config
