---
collections:
  - name: ansible.posix
    version: "2.1.0"
  - name: community.vmware
    version: "5.10.0"
  - name: vmware.vmware
    version: "2.9.0"
  - name: community.crypto
    version: "3.3.0"
  - name: community.hashi_vault
    version: "7.1.0"
  - name: community.general
    version: "11.4.9"
  - name: community.hrobot
    version: "2.7.2"
  - name: fedora.linux_system_roles
    version: "1.127.2"
  - name: lit.supplementary
    version: "1.40.0"
  - name: lit.foundational
    version: "1.31.0"
  - name: https://github.com/lightning-it/ansible-collection-rhel/releases/download/v1.21.0/lit-rhel-1.21.0.tar.gz
    type: url
  - name: lit.ubuntu
    version: "1.7.0"
  - name: https://github.com/lightning-it/ansible-collection-ocp/releases/download/v1.6.0/lit-ocp-1.6.0.tar.gz
    type: url
