---
collections:
  - name: ansible.posix
    version: "2.2.0"
  - name: community.vmware
    version: "6.2.0"
  - name: vmware.vmware
    version: "2.9.0"
  - name: community.crypto
    version: "3.2.2"
  - name: community.hashi_vault
    version: "7.1.0"
  - name: community.general
    version: "13.1.0"
  - name: fedora.linux_system_roles
    version: "1.125.4"
  - name: lit.supplementary
    version: "1.30.0"
  - name: lit.foundational
    version: "1.19.0"
  - name: lit.rhel
    version: "1.16.3"
  - name: lit.ubuntu
    version: "0.1.0"
