---
- name: Deploy DHCP Podman kube-play
  become: true
  hosts: "{{ dhcp_target | default('dhcp') }}"
  gather_facts: true
  roles:
    - role: lit.supplementary.dhcp_deploy
      tags:
        - dhcp
        - dhcp_deploy
